### ISSUE TITLE
Use the valid jdbc url in defaults

### ISSUE THREAD

**Issue by michalvanco** [cvengros/gooddata_datawarehouse#8]
you are using the `/gdc/dss/instances` url as default, but this one is old and you should use the `/gdc/datawarehouse/instances` instead

https://github.com/cvengros/gooddata_datawarehouse/blob/master/lib/gooddata_datawarehouse/datawarehouse.rb#L17

**Comment by cvengros** [comment]
Hi @michalvanco , `/datawarehouse/` doesn't work, I'm getting the following error from the jdbc driver
```
 Failure/Error: Unable to find matching line from backtrace
     Sequel::DatabaseConnectionError:
       Java::JavaSql::SQLException: DSS ID is missing or incorrect (maybe redundant '/' at the end), please use '/gdc/dss/instances/dss_id'. Example usage: jdbc:dss://na1.secure.gooddata.com/gdc/dss/instances/dss_id
```

**Comment by michalvanco** [comment]
well, sorry...that's just because you need to update the jdbc prefix as well (I forget to mention it)

**Comment by cvengros** [comment]
I'm afraid it's hard-wired somewhere deeper :/
```
Java::JavaSql::SQLException: No suitable driver found for jdbc:datawarehouse://secure.gooddata.com/gdc/datawarehouse/instances/z02116e70e5e1b5b83132303794b2219
```

**Comment by michalvanco** [comment]
one more point :)
```
jdbc:gdc:datawarehouse://" + host + "/gdc/datawarehouse/instances/" + instance_id
```

**Comment by cvengros** [comment]
That's better :)

fixed in https://github.com/cvengros/gooddata_datawarehouse/commit/f8647d07415811d4d4e83bf11b6d39c063972d28
